### ISSUE TITLE
what do i do

### ISSUE THREAD

**Issue by MrReddFlames** [Pi-Apps-Recreates/pi-apps-x86#19]
┏━━━┓                                           
┏━━┻━━━┻━━┓               
┃  ⬛⬛⬛ ┃  ▕ᑐ • ▁  ʌ                 
┃  ⬛⬛⬛ ┃  ▕  │   ╱‾╲▕ᑐ ▕ᑐ Ｓ - x86
┃  ⬛⬛⬛ ┃            ▕  ▕                  
╰━━━━━━━━━╯

Installing Tor Browser...
--2022-11-02 21:08:20--  https://sourceforge.net/projects/tor-browser.mirror/files/10.5.5/tor-browser-linux32-10.5.5_en-US.tar.xz/download
Resolving sourceforge.net (sourceforge.net)... 104.18.10.128, 104.18.11.128
Connecting to sourceforge.net (sourceforge.net)|104.18.10.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-02 21:08:25 ERROR 404: Not Found.

Failed to download!

Failed to install Tor Browser with install-32 script!
▲ Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/MCRaspRBX/pi-apps-x86/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
fatal: not a git repository (or any of the parent directories): .git

Close this window to exit.

**Comment by oxmc** [comment]
@MrReddFlames Pi-Apps-x86 is being fixed, for now please wait for us to fix it.
