### ISSUE TITLE
Add Among Us app

### ISSUE THREAD

**Issue by NoozAbooz** [Pi-Apps-Recreates/pi-apps-x86#7]
[AmongUs.zip](https://github.com/Pi-Apps-Recreates/pi-apps-x86/files/7110167/AmongUs.zip)

Not tested

**Comment by GizzyUwU** [comment]
Okay I will test at some point

**Comment by GizzyUwU** [comment]
I Cant Test Since I Dont Have Among US

**Comment by NoozAbooz** [comment]
https://steamunlocked.net/18-among-us-free-direct-download/

**Comment by GizzyUwU** [comment]
oh okay ill try

**Comment by GizzyUwU** [comment]
Installed Finished I Tried Opening It And It Opened Wine Desktop Then 
Closed

**Comment by NoozAbooz** [comment]
try it again

**Comment by GizzyUwU** [comment]
Ye that won't work I found a working one so among us would be added with method I found

**Comment by NoozAbooz** [comment]
What method did you find?

**Comment by GizzyUwU** [comment]
https://www.addictivetips.com/ubuntu-linux-tips/play-among-us-linux/

**Comment by GizzyUwU** [comment]
im using that guide setup but made it not need steam
