### ISSUE TITLE
No instructions on how to install, I've looked on yt but there are not videos on the x86 version, please help

### ISSUE THREAD

**Issue by BadRedJack** [Pi-Apps-Recreates/pi-apps-x86#9]

**Comment by oxmc** [comment]
On the website there is instructions: [website](https://www.pi-apps-x86.tk/#install)

**Comment by GizzyUwU** [comment]
Also sir there is one video for rn

**Comment by GizzyUwU** [comment]
I posted a install video

**Comment by oxmc** [comment]
Closing #9 as @BadRedJack has not responded, will reopen if needed.
